---
name: MsOffice-Word-HTML-Writer
version: 0.01
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
abstract: Writing documents for MsWord in HTML format
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  MIME::QuotedPrint: 0
  Module::Build: 0
  Params::Validate: 0
  Test::More: 0
provides:
  MsOffice::Word::HTML::Writer:
    file: lib/MsOffice/Word/HTML/Writer.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
