---
abstract: 'Writing documents for MsWord in HTML format'
author:
  - 'Laurent Dami <laurent.dami AT etat.ge.ch>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MsOffice-Word-HTML-Writer
provides:
  MsOffice::Word::HTML::Writer:
    file: lib/MsOffice/Word/HTML/Writer.pm
    version: 1.03
requires:
  Carp: 0
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  MIME::Types: 0
  Module::Build: 0
  Params::Validate: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
